[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"


[project]
name = "yaml-syntax"
version = "0.0.5"
license = "GPL-3.0-or-later"
authors = [
    {name = "EmadDeve20", email = "emaddeve20@gmail.com"},
]

maintainers = [
    {name = "EmadDeve20", email = "emaddeve20@gmail.com"},
]

description = "Check the syntax of a YAML file as you want to be. Checking the syntax of the YAML file is based on BaseModel of Pydantic."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "PyYAML>=6.0.3",
    "pydantic>=2.12.3",
]

keywords = ["yaml", "syntax", "pydantic"]

classifiers = [
    "Development Status :: 1 - Planning",

    "Programming Language :: Python :: 3.10",
]

[project.urls]
Homepage = "https://github.com/EmadDeve20/yaml-syntax"
Repository = "https://github.com/EmadDeve20/yaml-syntax"
Issues = "https://github.com/EmadDeve20/yaml-syntax/issues"

